### PR TITLE
remove + ignore composer.lock + update league/oauth2-client to version 2

### PR DESCRIPTION
**Pull request by it-can**
remove + ignore composer.lock + update league/oauth2-client to version 2

### CODE REVIEW

**Comment by it-can** [comment]
@Edwin-Luijten can you take a look?

**Comment by Edwin-Luijten** [comment]
Nice work, also good you removed the php 5.5 version =). Also, before I merge, could you remove the lock file from the repository?

**Comment by it-can** [comment]
I did remove the lock file...

**Comment by Edwin-Luijten** [comment]
Oops xD correct, I was looking at the wrong repository ...

**Comment by Edwin-Luijten** [comment]
bumped version to 1.1.0

**Pull request merged**
